spring:
  cloud:
    stream:
      function:
        bindings:
          sendCounter-out-0: output

      bindings:
        output:
          destination: counter
          producer:
            partition-count: 6
            poller:
              initial-delay: 5000
              fixed-delay: 6000

      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: true


