spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  cloud:
    stream:
      function:
        bindings:
          saveRequest-in-0: input
          saveRequest-out-0: output

      bindings:
        input:
          destination: application-request
          group: processor
          consumer:
            max-attempts: 3
            default-retryable: false
        downstream-A:
          producer:
            partition-count: 6
        downstream-B:
          producer:
            partition-count: 6

      kafka:
        binder:
          transaction:
            transaction-id-prefix: tx-
            producer:
              configuration:
                retries: 1
                acks: all
          #required-acks: all
        # bindings:
        #   downstream-A:
        #     producer:
        #       transactionManager: "chainedKafkaTransactionManager"
        #   downstream-B:
        #     producer:
        #       transactionManager: "chainedKafkaTransactionManager"

logging:
  level:
    org.springframework.transaction: trace
    org.springframework.kafka.transaction: debug

---
spring:
  config:
    activate:
      on-profile:
        - idea

  datasource:
    url: "jdbc:postgresql://localhost:5432/testDB"
    username: hung
    password: pass1234