spring:
  cloud:
    stream:
      function:
        bindings:
          consume-in-0: input
      bindings:
        input:
          destination: downstream-A,downstream-B
          group: consumer
      kafka:
        binder:
          configuration:
            isolation.level: read_committed


