---
apiVersion: v1
kind: Service
metadata:
  #namespace: postgres
  name: pgadmin-service
spec:
  type: ClusterIP
  selector:
    app: pgadmin
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: postgres
  name: pgadmin-deployment
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:6
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  PGADMIN_DEFAULT_EMAIL: kwonghung.yip@gmail.com
  PGADMIN_DEFAULT_PASSWORD: pass1234
  PGADMIN_LISTEN_ADDRESS: 0.0.0.0