apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  selector:
    matchLabels:
      app: processor-pod
  template:
    metadata:
      labels:
        app: processor-pod
    spec:
      containers:
        - name: springboot
          image: bugni/db-tran-processor
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
